allowBuilds:
  '@apollo/protobufjs': true
minimumReleaseAgeExclude:
  - '@types/node@22.20.0'
  # Renovate security update: @koa/cors@5.0.0
  - "@koa/cors@5.0.0"
minimumReleaseAge: 4320
publicHoistPattern:
  - '@apollo/utils.withrequired'
  - '@jest/types'
