allowBuilds:
  '@apollo/protobufjs': true
minimumReleaseAgeExclude:
  - '@types/node@22.20.0'
  # Renovate security update: koa@2.16.4
  - koa@2.16.4
minimumReleaseAge: 4320
publicHoistPattern:
  - '@apollo/utils.withrequired'
  - '@jest/types'
