version: 2.1

orbs:
  node: circleci/node@5.3.0

commands:
  setup-node:
    parameters:
      node-version:
        type: string
        default: "lts"
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Enable pnpm
          command: corepack enable pnpm
      - run: node --version
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile

jobs:
  NodeJS:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - setup-node:
          node-version: <<parameters.node-version>>
      - run: pnpm run build
      - run: pnpm run test:ci
      - store_test_results:
          path: junit.xml

  Full incremental delivery tests with graphql-js 17 canary:
    docker:
      - image: cimg/base:stable
    environment:
      INCREMENTAL_DELIVERY_TESTS_ENABLED: t
    steps:
      - setup-node:
          node-version: "18"
      - run: pnpm add --legacy-peer-deps graphql@17.0.0-alpha.1.canary.pr.3361.04ab27334641e170ce0e05bc927b972991953882
      - run: pnpm run test:ci
      - store_test_results:
          path: junit.xml

  Prettier:
    docker:
      - image: cimg/base:stable
    steps:
      - setup-node
      - run: pnpm run fmt:check

  Lint:
    docker:
      - image: cimg/base:stable
    steps:
      - setup-node
      - run: pnpm run lint

  Spell Check:
    docker:
      - image: cimg/base:stable
    steps:
      - setup-node
      - run: pnpm run spell-check

workflows:
  version: 2
  Build:
    jobs:
      - NodeJS:
          name: NodeJS << matrix.node-version >>
          matrix:
            parameters:
              node-version:
                - "22"
                - "24"
      - Full incremental delivery tests with graphql-js 17 canary
      - Prettier
      - Lint
      - Spell Check
