version: 2.1

orbs:
  node: circleci/node@5.3.0

commands:
  setup-node:
    parameters:
      node-version:
        type: string
        default: ''
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run: node --version
      - run:
          name: Install pnpm package manager
          command: |
            npm install --global corepack@latest
            corepack enable
            corepack prepare pnpm --activate
            pnpm config set store-dir .pnpm-store
      - node/install-packages:
          pkg-manager: pnpm

jobs:
  NodeJS:
    parameters:
      node-version:
        type: string
    docker:
    - image: cimg/base:stable
    steps:
      - setup-node:
          node-version: <<parameters.node-version>>
      - run: pnpm build
      - run: pnpm test:ci
      - store_test_results:
          path: junit.xml

  Full incremental delivery tests with graphql-js 17 canary:
    docker:
    - image: cimg/base:stable
    environment:
      INCREMENTAL_DELIVERY_TESTS_ENABLED: t
    steps:
      - setup-node:
          node-version: "22"
      # Install a prerelease of graphql-js 17 with incremental delivery support.
      # --legacy-peer-deps because nothing expects v17 yet.
      - run: pnpm add --frozen-lockfile=false graphql@17.0.0-alpha.9 @yaacovcr/transform@0.0.8
      - run: pnpm test:ci
      - store_test_results:
          path: junit.xml

  Prettier:
    docker:
    - image: cimg/base:stable
    steps:
      - setup-node
      - run: pnpm prettier-check

  Lint:
    docker:
    - image: cimg/base:stable
    steps:
      - setup-node
      - run: pnpm lint

  Spell Check:
    docker:
    - image: cimg/base:stable
    steps:
      - setup-node
      - run: pnpm spell-check

workflows:
  version: 2
  Build:
    jobs:
      - NodeJS:
          name: NodeJS << matrix.node-version >>
          matrix:
            parameters:
              node-version:
                - "22"
                - "24"
      - Full incremental delivery tests with graphql-js 17 canary
      - Prettier
      - Lint
      - Spell Check